// Generated by gencpp from file bionic_hand/BulkGetItem.msg
// DO NOT EDIT!


#ifndef BIONIC_HAND_MESSAGE_BULKGETITEM_H
#define BIONIC_HAND_MESSAGE_BULKGETITEM_H

#include <ros/service_traits.h>


#include <bionic_hand/BulkGetItemRequest.h>
#include <bionic_hand/BulkGetItemResponse.h>


namespace bionic_hand
{

struct BulkGetItem
{

typedef BulkGetItemRequest Request;
typedef BulkGetItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BulkGetItem
} // namespace bionic_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bionic_hand::BulkGetItem > {
  static const char* value()
  {
    return "f0b74b4d53178e0d0ede26a30b687544";
  }

  static const char* value(const ::bionic_hand::BulkGetItem&) { return value(); }
};

template<>
struct DataType< ::bionic_hand::BulkGetItem > {
  static const char* value()
  {
    return "bionic_hand/BulkGetItem";
  }

  static const char* value(const ::bionic_hand::BulkGetItem&) { return value(); }
};


// service_traits::MD5Sum< ::bionic_hand::BulkGetItemRequest> should match
// service_traits::MD5Sum< ::bionic_hand::BulkGetItem >
template<>
struct MD5Sum< ::bionic_hand::BulkGetItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::BulkGetItem >::value();
  }
  static const char* value(const ::bionic_hand::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::BulkGetItemRequest> should match
// service_traits::DataType< ::bionic_hand::BulkGetItem >
template<>
struct DataType< ::bionic_hand::BulkGetItemRequest>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::BulkGetItem >::value();
  }
  static const char* value(const ::bionic_hand::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bionic_hand::BulkGetItemResponse> should match
// service_traits::MD5Sum< ::bionic_hand::BulkGetItem >
template<>
struct MD5Sum< ::bionic_hand::BulkGetItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::BulkGetItem >::value();
  }
  static const char* value(const ::bionic_hand::BulkGetItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::BulkGetItemResponse> should match
// service_traits::DataType< ::bionic_hand::BulkGetItem >
template<>
struct DataType< ::bionic_hand::BulkGetItemResponse>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::BulkGetItem >::value();
  }
  static const char* value(const ::bionic_hand::BulkGetItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIONIC_HAND_MESSAGE_BULKGETITEM_H
