// Generated by gencpp from file bionic_hand/ControlCommands.msg
// DO NOT EDIT!


#ifndef BIONIC_HAND_MESSAGE_CONTROLCOMMANDS_H
#define BIONIC_HAND_MESSAGE_CONTROLCOMMANDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bionic_hand
{
template <class ContainerAllocator>
struct ControlCommands_
{
  typedef ControlCommands_<ContainerAllocator> Type;

  ControlCommands_()
    : ID(0)
    , PWM(0.0)  {
    }
  ControlCommands_(const ContainerAllocator& _alloc)
    : ID(0)
    , PWM(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _ID_type;
  _ID_type ID;

   typedef double _PWM_type;
  _PWM_type PWM;





  typedef boost::shared_ptr< ::bionic_hand::ControlCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bionic_hand::ControlCommands_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommands_

typedef ::bionic_hand::ControlCommands_<std::allocator<void> > ControlCommands;

typedef boost::shared_ptr< ::bionic_hand::ControlCommands > ControlCommandsPtr;
typedef boost::shared_ptr< ::bionic_hand::ControlCommands const> ControlCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bionic_hand::ControlCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bionic_hand::ControlCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bionic_hand::ControlCommands_<ContainerAllocator1> & lhs, const ::bionic_hand::ControlCommands_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.PWM == rhs.PWM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bionic_hand::ControlCommands_<ContainerAllocator1> & lhs, const ::bionic_hand::ControlCommands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bionic_hand

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bionic_hand::ControlCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bionic_hand::ControlCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bionic_hand::ControlCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bionic_hand::ControlCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bionic_hand::ControlCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bionic_hand::ControlCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bionic_hand::ControlCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0710b5797f0353030d05fc8a9f52589b";
  }

  static const char* value(const ::bionic_hand::ControlCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0710b5797f035303ULL;
  static const uint64_t static_value2 = 0x0d05fc8a9f52589bULL;
};

template<class ContainerAllocator>
struct DataType< ::bionic_hand::ControlCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bionic_hand/ControlCommands";
  }

  static const char* value(const ::bionic_hand::ControlCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bionic_hand::ControlCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ID\n"
"float64 PWM\n"
;
  }

  static const char* value(const ::bionic_hand::ControlCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bionic_hand::ControlCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.PWM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bionic_hand::ControlCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bionic_hand::ControlCommands_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "PWM: ";
    Printer<double>::stream(s, indent + "  ", v.PWM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIONIC_HAND_MESSAGE_CONTROLCOMMANDS_H
