// Generated by gencpp from file bionic_hand/GetPosition.msg
// DO NOT EDIT!


#ifndef BIONIC_HAND_MESSAGE_GETPOSITION_H
#define BIONIC_HAND_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <bionic_hand/GetPositionRequest.h>
#include <bionic_hand/GetPositionResponse.h>


namespace bionic_hand
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace bionic_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bionic_hand::GetPosition > {
  static const char* value()
  {
    return "b532ace3b383dc4c9e64687156423ac0";
  }

  static const char* value(const ::bionic_hand::GetPosition&) { return value(); }
};

template<>
struct DataType< ::bionic_hand::GetPosition > {
  static const char* value()
  {
    return "bionic_hand/GetPosition";
  }

  static const char* value(const ::bionic_hand::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::bionic_hand::GetPositionRequest> should match
// service_traits::MD5Sum< ::bionic_hand::GetPosition >
template<>
struct MD5Sum< ::bionic_hand::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::GetPosition >::value();
  }
  static const char* value(const ::bionic_hand::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::GetPositionRequest> should match
// service_traits::DataType< ::bionic_hand::GetPosition >
template<>
struct DataType< ::bionic_hand::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::GetPosition >::value();
  }
  static const char* value(const ::bionic_hand::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bionic_hand::GetPositionResponse> should match
// service_traits::MD5Sum< ::bionic_hand::GetPosition >
template<>
struct MD5Sum< ::bionic_hand::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::GetPosition >::value();
  }
  static const char* value(const ::bionic_hand::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::GetPositionResponse> should match
// service_traits::DataType< ::bionic_hand::GetPosition >
template<>
struct DataType< ::bionic_hand::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::GetPosition >::value();
  }
  static const char* value(const ::bionic_hand::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIONIC_HAND_MESSAGE_GETPOSITION_H
