// Generated by gencpp from file bionic_hand/SetPWM.msg
// DO NOT EDIT!


#ifndef BIONIC_HAND_MESSAGE_SETPWM_H
#define BIONIC_HAND_MESSAGE_SETPWM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bionic_hand
{
template <class ContainerAllocator>
struct SetPWM_
{
  typedef SetPWM_<ContainerAllocator> Type;

  SetPWM_()
    : id(0)
    , pwm(0)  {
    }
  SetPWM_(const ContainerAllocator& _alloc)
    : id(0)
    , pwm(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int32_t _pwm_type;
  _pwm_type pwm;





  typedef boost::shared_ptr< ::bionic_hand::SetPWM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bionic_hand::SetPWM_<ContainerAllocator> const> ConstPtr;

}; // struct SetPWM_

typedef ::bionic_hand::SetPWM_<std::allocator<void> > SetPWM;

typedef boost::shared_ptr< ::bionic_hand::SetPWM > SetPWMPtr;
typedef boost::shared_ptr< ::bionic_hand::SetPWM const> SetPWMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bionic_hand::SetPWM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bionic_hand::SetPWM_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bionic_hand::SetPWM_<ContainerAllocator1> & lhs, const ::bionic_hand::SetPWM_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pwm == rhs.pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bionic_hand::SetPWM_<ContainerAllocator1> & lhs, const ::bionic_hand::SetPWM_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bionic_hand

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bionic_hand::SetPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bionic_hand::SetPWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bionic_hand::SetPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bionic_hand::SetPWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bionic_hand::SetPWM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bionic_hand::SetPWM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bionic_hand::SetPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7dcb9d04de9857b62a1d688544986dcd";
  }

  static const char* value(const ::bionic_hand::SetPWM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7dcb9d04de9857b6ULL;
  static const uint64_t static_value2 = 0x2a1d688544986dcdULL;
};

template<class ContainerAllocator>
struct DataType< ::bionic_hand::SetPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bionic_hand/SetPWM";
  }

  static const char* value(const ::bionic_hand::SetPWM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bionic_hand::SetPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"int32 pwm\n"
;
  }

  static const char* value(const ::bionic_hand::SetPWM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bionic_hand::SetPWM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPWM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bionic_hand::SetPWM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bionic_hand::SetPWM_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pwm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIONIC_HAND_MESSAGE_SETPWM_H
