// Generated by gencpp from file bionic_hand/SyncGetPosition.msg
// DO NOT EDIT!


#ifndef BIONIC_HAND_MESSAGE_SYNCGETPOSITION_H
#define BIONIC_HAND_MESSAGE_SYNCGETPOSITION_H

#include <ros/service_traits.h>


#include <bionic_hand/SyncGetPositionRequest.h>
#include <bionic_hand/SyncGetPositionResponse.h>


namespace bionic_hand
{

struct SyncGetPosition
{

typedef SyncGetPositionRequest Request;
typedef SyncGetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGetPosition
} // namespace bionic_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bionic_hand::SyncGetPosition > {
  static const char* value()
  {
    return "4a5a90af26ce6360c45e1980f134941b";
  }

  static const char* value(const ::bionic_hand::SyncGetPosition&) { return value(); }
};

template<>
struct DataType< ::bionic_hand::SyncGetPosition > {
  static const char* value()
  {
    return "bionic_hand/SyncGetPosition";
  }

  static const char* value(const ::bionic_hand::SyncGetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::bionic_hand::SyncGetPositionRequest> should match
// service_traits::MD5Sum< ::bionic_hand::SyncGetPosition >
template<>
struct MD5Sum< ::bionic_hand::SyncGetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::SyncGetPosition >::value();
  }
  static const char* value(const ::bionic_hand::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::SyncGetPositionRequest> should match
// service_traits::DataType< ::bionic_hand::SyncGetPosition >
template<>
struct DataType< ::bionic_hand::SyncGetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::SyncGetPosition >::value();
  }
  static const char* value(const ::bionic_hand::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bionic_hand::SyncGetPositionResponse> should match
// service_traits::MD5Sum< ::bionic_hand::SyncGetPosition >
template<>
struct MD5Sum< ::bionic_hand::SyncGetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bionic_hand::SyncGetPosition >::value();
  }
  static const char* value(const ::bionic_hand::SyncGetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bionic_hand::SyncGetPositionResponse> should match
// service_traits::DataType< ::bionic_hand::SyncGetPosition >
template<>
struct DataType< ::bionic_hand::SyncGetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::bionic_hand::SyncGetPosition >::value();
  }
  static const char* value(const ::bionic_hand::SyncGetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIONIC_HAND_MESSAGE_SYNCGETPOSITION_H
