middle_finger:
        dt: 0.03
        forward:
                M_joint:
                        N_M: 120
                        nu_M: 22
                        LAMBDA_M: 1.3
                        deadTimeSteps_M: 0
                P_joint:
                        N_P: 120
                        nu_P: 15
                        LAMBDA_P: 4
                        deadTimeSteps_P: 0
                D_joint:
                        N_D: 60
                        nu_D: 2
                        LAMBDA_D: 1.05
                        deadTimeSteps_D: 0
        reverse:
                M_joint:
                        N_M_rev: 8
                        nu_M_rev: 4
                        LAMBDA_M_rev: 10
                        deadTimeSteps_M_rev: 0
                P_joint:
                        N_P_rev: 12
                        nu_P_rev: 5
                        LAMBDA_P_rev:  10
                        deadTimeSteps_P_rev: 2
                D_joint:
                        N_D_rev: 8
                        nu_D_rev: 4
                        LAMBDA_D_rev: 35
                        deadTimeSteps_D_rev: 2
                