middle_finger:
        dt: 0.01
        M_joint:
                kp: 0.2
                ki: 0.1
                kd: 0.001
        P_joint:
                kp: 0.2
                ki: 0.05
                kd: 0.01
        D_joint:
                kp: 0.2
                ki: 0.11
                kd: 0.001
                
