middle_finger:
        M_joint:
                kp: 0.1
                ki: 0.001
                kd: 0.001
        P_joint:
                kp: 0.1
                ki: 0.001
                kd: 0.001
        D_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
                
