middle_finger:
        M_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
        P_joint:
                kp: 0.001
                ki: 0
                kd: 0
        D_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
index_finger:
        M_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
        P_joint:
                kp: 0.001
                ki: 0
                kd: 0
        D_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
thumb_finger:
        M_joint:
                kp: 20
                ki: 0.1
                kd: 0.001
        P_joint:
                kp: 0.001
                ki: 0
                kd: 0
        D_joint: #ingnore this joint for thumb
                kp: 20
                ki: 0.1
                kd: 0.001
                

                
