(cl:defpackage bionic_hand-msg
  (:use )
  (:export
   "<BULKSETITEM>"
   "BULKSETITEM"
   "<CONTROLCOMMANDS>"
   "CONTROLCOMMANDS"
   "<FINGERJOINTS>"
   "FINGERJOINTS"
   "<FINGERPOS>"
   "FINGERPOS"
   "<SETPWM>"
   "SETPWM"
   "<SETPOSITION>"
   "SETPOSITION"
   "<SYNCSETPOSITION>"
   "SYNCSETPOSITION"
  ))

